# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MaePlanejaCliente' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaePlanejaCliente
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

  target 'MaePlanejaClienteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MaePlanejaClienteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
